"""Add User model, roles, and user_id to components

Revision ID: 46b93d125112
Revises: ffd95f9cc5ab
Create Date: 2026-06-11 16:22:27.684130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "46b93d125112"
down_revision: Union[str, Sequence[str], None] = "ffd95f9cc5ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # 1. Add column as nullable first
    op.add_column("components", sa.Column("user_id", sa.Integer(), nullable=True))

    # 2. Create a default admin user for existing components
    op.execute(
        "INSERT INTO users (username, email, hashed_password, role, created_at) "
        "VALUES ('default_admin', 'admin@toolboxdb.local', 'dummy_hash', 'admin', NOW())"
    )

    # 3. Update existing components to belong to this default user
    op.execute(
        "UPDATE components SET user_id = (SELECT id FROM users WHERE username='default_admin' LIMIT 1)"
    )

    # 4. Alter column to be NOT NULL
    op.alter_column("components", "user_id", nullable=False)

    # 5. Add foreign key
    op.create_foreign_key(
        "fk_components_users_id",
        "components",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "components", type_="foreignkey")
    op.drop_column("components", "user_id")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
