"""add user_id to invoices

Revision ID: a16dc866cacf
Revises: 46b93d125112
Create Date: 2026-06-11 16:53:02.134491

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a16dc866cacf"
down_revision: Union[str, Sequence[str], None] = "46b93d125112"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column("invoices", sa.Column("user_id", sa.Integer(), nullable=True))

    # Update existing invoices to assign them to the first admin user
    op.execute(
        "UPDATE invoices SET user_id = (SELECT id FROM users WHERE role='admin' LIMIT 1) WHERE user_id IS NULL"
    )

    # Alter column to be NOT NULL
    op.alter_column("invoices", "user_id", nullable=False)

    op.create_foreign_key(
        None, "invoices", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "invoices", type_="foreignkey")
    op.drop_column("invoices", "user_id")
    # ### end Alembic commands ###
