"""Initial migration

Revision ID: ffd95f9cc5ab
Revises:
Create Date: 2026-06-10 12:14:42.014629

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ffd95f9cc5ab"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_parts_category"), table_name="parts")
    op.drop_index(op.f("idx_parts_name"), table_name="parts")
    op.drop_index(op.f("idx_parts_user_id"), table_name="parts")
    op.execute("DROP TABLE parts CASCADE")
    op.drop_index(op.f("idx_stock_movements_part_id"), table_name="stock_movements")
    op.drop_index(op.f("idx_stock_movements_user_id"), table_name="stock_movements")
    op.execute("DROP TABLE stock_movements CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_movements",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("part_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("delta", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "reason",
            sa.TEXT(),
            server_default=sa.text("'Manuel guncelleme'::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.UUID(),
            server_default=sa.text("auth.uid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["parts.id"],
            name=op.f("stock_movements_part_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_stock_movements_user_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("stock_movements_pkey")),
    )
    op.create_index(
        op.f("idx_stock_movements_user_id"),
        "stock_movements",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_stock_movements_part_id"),
        "stock_movements",
        ["part_id"],
        unique=False,
    )
    op.create_table(
        "parts",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("category", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "quantity",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "min_quantity",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "unit",
            sa.TEXT(),
            server_default=sa.text("'adet'::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "location",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("photo_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.UUID(),
            server_default=sa.text("auth.uid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint("min_quantity >= 0", name=op.f("parts_min_quantity_check")),
        sa.CheckConstraint("quantity >= 0", name=op.f("parts_quantity_check")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_parts_user_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("parts_pkey")),
    )
    op.create_index(op.f("idx_parts_user_id"), "parts", ["user_id"], unique=False)
    op.create_index(op.f("idx_parts_name"), "parts", ["name"], unique=False)
    op.create_index(op.f("idx_parts_category"), "parts", ["category"], unique=False)
    # ### end Alembic commands ###
